const constants = {
    RUN_BUILD: "Run build",
    REBUILD: "Rebuild",
    TO_SETTINGS: "Settings",
    SITE_NAME: "School CI server",
    ERROR_WARNING: "Запрос завершился с ошибкой",
    ERROR_REPONAME: "Необходимо заполнить наименование репозитория",
    ERROR_BUILDCOMMAND: "Необходимо заполнить команду для сборки",
    ERROR_COMMITHASH: "Необходимо заполнить хэш коммита",
    POPUP: "POPUP",
    SHOW_END: "SHOW_END",
    ADD_LIMIT: 5,
    SETTINGS: "SETTINGS",
    BUILDS: "BUILDS",
    MORE_BUILDS: "MORE_BUILDS",
    NEW_BUILD: "NEW_BUILD",
    DETAIL_BUILD: "DETAIL_BUILD",
    DETAIL_LOG: "DETAIL_LOG",
    ERROR_BUILD: "ERROR_BUILD",
    FETCHING_STATUS: "FETCHING_STATUS",
    LOAD_SETTINGS: "LOAD_SETTINGS",
    SERVER_API: "http://localhost:8000/api",
    MONTHS: [
        "янв",
        "февр",
        "март",
        "апр",
        "май",
        "июня",
        "июля",
        "авг",
        "сент",
        "окт",
        "нояб",
        "дек",
    ],
};

export default constants;
